server:
  port: ${PORT:8080}

spring:
  application:
    name: our-backend-project

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL USER}
    password: ${MYSQL PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  hugging face:
    api:
      token: ${HUGGING FACE_API_TOKEN}